exp:
    name: 00_02
    names_exp_delete: ['tmp', 'train_00_02']
    idx_device: 2
    train:
        batch_size: 1
        select_mods: False
        optimizer:
            name: adam
            lr: 1e-6
    val:
        batch_size: 1

    test:
        batch_size: 1

dataset:
    name: lumenDataset
    path: ./data/iSNAP

model:
    name: unet3d_model
    w_focal: 0.5

net:
    in_channels: 1
    out_channels: 1
    model_depth: 4
