exp:
    name: 00_04
    names_exp_delete: ['tmp', 'train_00_04']
    idx_device: 2
    train:
        batch_size: 4
        select_mods: False
        optimizer:
            name: adam
            lr: 1e-5
    val:
        batch_size: 1

    test:
        batch_size: 1

dataset:
    name: lumenDataset
    path: ./data/iSNAP

model:
    name: unet3d_model
    w_focal: 0.5

net:
    in_channels: 1
    out_channels: 1
    model_depth: 4
