exp:
    name: 00_00
    names_exp_delete: ['tmp', '00_00']
    idx_device: 2
    train:
        batch_size: 4
        select_mods: False
    val:
        batch_size: 1

    test:
        batch_size: 1

dataset:
    name: lumenDataset
    path: ./data/iSNAP

model:
    name: unet3d_model

net:
    in_channels: 1
    out_channels: 1
    model_depth: 4
