exp:
    name: 02_02
    names_exp_delete: ['tmp', 'train_02_00']
    idx_device: [0,1]
    customize_dataloader: False
    train:
        batch_size: 4
        select_mods: False
        optimizer:
            name: adam
            lr: 1e-5
    val:
        batch_size: 1
        n_epochs_once: 5

    test:
        batch_size: 1

dataset:
    name: miccaitofDataset
    path: ./data/CAS2023_training
    hps: 32
    shape_patch: 64

model:
    name: unet3d_model
    w_focal: 0.5

net:
    in_channels: 1
    out_channels: 1
    model_depth: 4