exp:
    name: 03_01
    names_exp_delete: ['tmp', 'train_03_01']
    idx_device: 0
    customize_dataloader: True
    nnunet_result: 
        path: /home/kaiyu/project/nnUNet_dataset/nnUNet_results/Dataset301_SMRATOF/nnUNetTrainer__nnUNetPlans__3d_fullres
        fold: 0
        model: 3d_fullres

    train:
        path_model_trained: null
        batch_size: 1
        select_mods: False
        optimizer:
            name: adam
            lr: 3e-4
            adam:
                weight_decay: 1e-5
    val:
        skip_initial_val: True
        batch_size: 1
        n_epochs_once: 5

    test:
        batch_size: 1
        path_model_trained: null

dataset:
    name: miccaimonaiDataset
    path: ./data/MICCAI_MONAI/MICCAI_CAS_2023.json

model:
    name: nnunet_model
    ws_loss:
        cldiceloss: 1
        focal: 0
    w_focal: 0.5