exp:
    name: 03_00
    names_exp_delete: ['tmp', 'train_03_00']
    idx_device: 0
    customize_dataloader: False
    train:
        path_model_trained: ./save/SMRA_nnUnet.pth
        batch_size: 1
        select_mods: False
        optimizer:
            name: adam
            lr: 3e-4
            adam:
                weight_decay: 1e-5
    val:
        skip_initial_val: False
        batch_size: 1
        n_epochs_once: 2

    test:
        batch_size: 1
        path_model_trained: ./save/SMRA_nnUnet.pth

dataset:
    name: miccaitofDataset
    path: ./data/CAS2023_training
    hps: 32
    shape_patch: 64

model:
    name: nnunet_model
    ws_loss:
        focal: 0.5
        diceloss: 0.5
    w_focal: 0.5