exp:
    name: 03_00
    names_exp_delete: ['tmp', 'train_03_00']
    idx_device: 2
    customize_dataloader: False
    train:
        path_model_trained: null
        batch_size: 1
        select_mods: False
        optimizer:
            name: adam
            lr: 3e-4
            adam:
                weight_decay: 1e-5
    val:
        skip_initial_val: False
        batch_size: 1
        n_epochs_once: 2

    test:
        batch_size: 1
        path_model_trained: null

dataset:
    name: miccaitofDataset
    path: ./data/CAS2023_training
    shape_patch: [224, 224, 48]

model:
    name: nnunet_model
    ws_loss:
        cldiceloss: 1
        focal: 0
    w_focal: 0.5