exp:
    name: 03_03_test
    names_exp_delete: ['tmp', 'train_03_03_test']
    idx_device: 3
    customize_dataloader: True
    nnunet_result: 
        path: /home/kaiyu/project/nnUNet_dataset/nnUNet_results/Dataset301_SMRATOF/nnUNetTrainer__nnUNetPlans__3d_fullres
        fold: 0
        model: 3d_fullres
        weights: ./save/SMRA_nnUnet.pth

    train:
        path_model_trained: null
        batch_size: 1
        select_mods: False
        optimizer:
            name: adam
            lr: 3e-4
            adam:
                weight_decay: 1e-5
    val:
        skip_initial_val: True
        batch_size: 1
        n_epochs_once: 10

    test:
        batch_size: 1
        path_model_trained: null
        n_repeat: 1
        confusion_matrix:
        classification_curve:
            enable: true
        metrics_all_cases:
            enable: true
        dice: true
        save_seg:
            enable: true

dataset:
    name: smrastenosisDataset
    path: ./data/SMRA_MONAI_npy/MICCAI_CAS_2023_extra.json
    num_cache_train: 1
    num_cache_val: 2  
    num_samples: 2

model:
    name: nnunet_model
    ws_loss:
        cldiceloss: 0.5
        focal: 0.0
        lumen: 0.0
    w_focal: 0.5