dataset:
    path: ./data/iSNAP
    auglist:
    hps: 32
    shape_patch: 64
    output_pos: False
    dim: 3
    batch_size: 4
    n_channels_img: 1
    mods: ['S104']
    max_pts_per_case: 500
    raw_vesname: 'tracing_raw_ves_TH_'
    vesname: 'tracing_ves_TH_'
